version: '3.7'
services:
  mysql8-container:
    container_name: mysql8-container
    image: mysql:8.2.0    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ReadBooks
    ports:
      - 3307:3306
    #volumes: 
    #- ./sql/shopapp.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - readbook-network 
  phpmyadmin8-container:
    image: phpmyadmin/phpmyadmin    
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container      
    ports:
      - "8100:80"
    environment:
      PMA_HOST: mysql8-container 
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - readbook-network
networks:
  readbook-network:
    name: readbook-network
    driver: bridge

#chạy câu lệnh sau để tạo container mysql
#docker-compose -f ./deployment.yaml up -d mysql8-container
#delete container
#docker-compose -f ./deployment.yaml rm -s -f mysql8-container

#chạy câu lệnh sau để tạo phpmyadmin
#docker-compose -f ./deployment.yaml up -d phpmyadmin8-container
#delete container
#docker-compose -f ./deployment.yaml rm -s -f phpmyadmin8-container
